import {
  Bot,
  Bug,
  Braces,
  FileCode2,
  Gauge,
  GitCompareArrows,
  Regex,
  ScrollText,
  Database,
  LayoutTemplate,
} from 'lucide-react';
export const aiTools = [
  {
    slug: 'chat',
    title: 'AI Chat',
    description: 'Ask technical questions and build solutions.',
    icon: Bot,
    mode: 'chat',
  },
  {
    slug: 'code-generator',
    title: 'Code Generator',
    description: 'Turn requirements into production code.',
    icon: Braces,
    mode: 'generate',
  },
  {
    slug: 'debug-assistant',
    title: 'Debug Assistant',
    description: 'Find root causes and produce safe fixes.',
    icon: Bug,
    mode: 'debug',
  },
  {
    slug: 'code-explainer',
    title: 'Code Explainer',
    description: 'Understand code at any experience level.',
    icon: FileCode2,
    mode: 'explain',
  },
  {
    slug: 'code-optimizer',
    title: 'Code Optimizer',
    description: 'Improve performance, security, and clarity.',
    icon: Gauge,
    mode: 'optimize',
  },
  {
    slug: 'documentation',
    title: 'Documentation',
    description: 'Generate README and API documentation.',
    icon: ScrollText,
    mode: 'document',
  },
  {
    slug: 'code-converter',
    title: 'Code Converter',
    description: 'Translate code between languages.',
    icon: GitCompareArrows,
    mode: 'convert',
  },
  {
    slug: 'sql-generator',
    title: 'SQL Generator',
    description: 'Build and explain safe SQL.',
    icon: Database,
    mode: 'sql',
  },
  {
    slug: 'regex-generator',
    title: 'Regex Generator',
    description: 'Generate, explain, and test regular expressions.',
    icon: Regex,
    mode: 'regex',
  },
  {
    slug: 'ui-generator',
    title: 'UI Generator',
    description: 'Create responsive frontend components.',
    icon: LayoutTemplate,
    mode: 'ui',
  },
];
